config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'index#index'
  get "/auth/:provider/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: :owner_id

  # @param [Post] exclude_post 除外したいPost
  # @return [ActiveRecord::Relation<Post>] 指定したものを除く最新投稿順のPost
  def self.new_arrival_posts(exclude_post)
    self.where.not(id: exclude_post&.id).order(created_at: :desc)
  end

  # @return [Post] ピックアップポスト、ロジックは書きたかったが、とりあえずfirst
  def self.pickup_post(current_post:,new_arrival_posts:)
    Post.first
  end

  # @return [ActiveRecord::Relation<Post>] 関連ポスト、とりあえず指定したものを除いた1,2,3
  def self.relation_posts(post)
    Post.where.not(id:post.id).where(id: [1,2,3])
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]
    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :session_user

  private

  # @return [User] セッション情報に連動するUserオブジェクトを返却する。DBからのSelectを複数回行いたくないのでインスタンス変数化
  def session_user
    @memorize_session_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!session_user
  end

  def require_login
    return if logged_in?
    redirect_to root_path, notice: "ログインしてください"
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[ new, edit]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @new_arrival_posts = Post.new_arrival_posts(@post)
    @relation_posts = Post.relation_posts(@post)
    pickup_post = Post.pickup_post(current_post: @post, new_arrival_posts: @new_arrival_posts)
    @recommend_posts = Post.new_arrival_posts(pickup_post)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    @new_arrival_posts = Post.new_arrival_posts(@post)
    @relation_posts = Post.relation_posts(@post)
    @recommend_posts = Post.new_arrival_posts(nil)
  end

  ### 中略 ###

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def post_params
      params.require(:post).permit(:owner_id, :title, :homepage_url, :message)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash!(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, notice: "ログインしました"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/index/index.html.erb
<div class="text-center">PerlCGI掲示板をモチーフにしたサンプルアプリケーションです</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuestBookBoard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-green-400">
<div class="container mx-auto px-1">
  <div class="divide-y divide-black divide-opacity-25">
    <div class="text-center text-3xl py-3">ゲストブック</div>
    <div class="text-center text-1 py-1">
      [<a href="/posts">トップに戻る</a>]
      [<a href="/">留意事項</a>]
      [<a href="<%= new_post_path %>">投稿する</a>]
    </div>
    <% if flash.notice.present? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <span class="block sm:inline"><%= flash.notice %></span>
      </div>
    <% end %>
    <div></div>
  </div>
</div>
<%= yield %>
<hr class="border-black border-1">
<div class="text-right">
  <% if logged_in? %>
    <%= session_user.name %>さんでログイン中 [<%= link_to "ログアウト", logout_path, class: "text-blue-500 hover:text-blue-800", method: :delete %>]
  <% else %>
    <%= link_to "GitHubでログイン", "/auth/github", class: "text-blue-500 hover:text-blue-800", method: :post %>
  <% end %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="container mx-auto px-1">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :owner_id, :value => session_user.id %>

    <table class="text-left p-3">
      <tr>
        <th class="p-1">タイトル：</th>
        <td class="p-1"><%= form.text_field :title %></td>
      </tr>
      <tr>
        <th class="p-1">URL：</th>
        <td class="p-1"><%= form.text_field :homepage_url %></td>
      </tr>
      <tr>
        <th colspan="2" class="p-1">
          メッセージ：<br>
          <%= form.text_area :message, :class => "w-full" %><br>

          <div class="actions">
            <%= form.submit value: "送信する" %>
          </div>
        </th>
      </tr>
    </table>
  <% end %>
</div>

app/views/posts/_new_arrival_top3.html.erb
<%# new_arrival_posts: 呼び出し側から与えられる新着順に並んだPosts %>
<hr class="border-black border-1">
<div class="text-center">
  直近の投稿は
  <% new_arrival_posts.take(3).each do |post|  %>
    『<%= link_to(post.title,post_path(post.id)) %>』
  <% end %>
  です。
</div>

app/views/posts/_recommend_post.html.erb
<%# recommend_posts: 呼び出し側から与えられるおすすめのPosts %>
<hr class="border-black border-1">
<div class="text-center">
  おすすめの投稿は
  <% recommend_posts.each do |post|  %>
    『<%= link_to(post.title,post_path(post.id)) %>』
  <% end %>
  です。
</div>

app/views/posts/_relation_post.html.erb
<%# relation_posts: 呼び出し側から与えられる新着順に並んだPosts %>
<hr class="border-black border-1">
<div class="text-center">
  関連の投稿は
  <% relation_posts.each do |post|  %>
    『<%= link_to(post.title,post_path(post.id)) %>』
  <% end %>
  です。
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>
<%= render 'new_arrival_top3', new_arrival_posts: @new_arrival_posts %>

app/views/posts/index.html.erb
<div class="container mx-auto px-1 divide-y divide-black divide-opacity-25">
  <% @posts.each do |post| %>
    <div class="py-3">
      <div class="font-bold">
        [<%= post.id %>]<%= post.title %> - <%= post.user.name %>さん [<a href="<%= edit_post_path(post.id) %>">編集</a>]
      </div>
      <div class="py-1">
        <%= simple_format(post.message) %>
      </div>
    </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="container mx-auto px-1">
  <p id="notice"><%= notice %></p>

  <div class="py-3">
    <div class="font-bold">
      [<%= @post.id %>]<%= @post.title %> - <%= @post.user.name %>さん
    </div>
    <div class="py-1">
      <%= simple_format(@post.message) %>
    </div>
  </div>
</div>
<%= render 'new_arrival_top3', new_arrival_posts: @new_arrival_posts %>
<%= render 'relation_post', relation_posts: @relation_posts %>
<%= render 'recommend_post', recommend_posts: @recommend_posts %>